apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-engine
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/default-backend: eval-engine
spec:
  rules:
  - host: engine
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eval-engine
            port:
              number: 50051
  ingressClassName: nginx
  tls:
  # This secret must exist beforehand
  # The cert must also contain the subj-name grpctest.dev.mydomain.com
  # https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/PREREQUISITES.md#tls-certificates
  - secretName: tls-secret
    hosts:
      - engine.eval.net