apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:

  hostAliases:
  # - ip: "192.168.1.8"
  #   hostnames:
  #   - "registry.other.net"
  containers:

  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    env:
      - name: GIT_TOKEN
        value: "969c5cb1eaee59d878648cb862bef551cac70d34"
      - name: GIT_PULL_METHOD
        value: "http"
    args: [
    "--insecure",
    "--insecure-pull",
    "--skip-tls-verify",
    "--destination=kind-registry:5000/test:bar",
#    "--context=git://gitea-service.gitea-repo.svc.cluster.local:3000/mav/eval.git#refs/heads/main#8adc1aa2494ad4debba2dd795725223f251ff98a",
    "--context=git://gitea-service.gitea-repo.svc.cluster.local:3000/mav/eval.git",
    "--dockerfile=dockerfile",
    ]
    volumeMounts:
      # - name: data
      #   mountPath: /data
      - name: docker-config
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    # - name: data
    #   hostPath:
    #     path: /data  # matches kind containerPath:
    - name: docker-config
      projected:
        sources:
          - secret:
              name: regcred
              items:
                - key: .dockerconfigjson
                  path: config.json
