apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: localhost:5000/eval:302b8d1d-57be-4120-b575-0fdde2d97974
    command: ["/app/actions/wrapper/wrapper_/wrapper"]
    # command: ["/bin/ls"]
    # args: ["-lR", "/app"]
#    command: ["/app/test"]
    imagePullPolicy: Always
  restartPolicy: Never
