apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: localhost:5000/eval:2057bc47-d332-4059-9f67-8d145a8002f0
    command: ["/app/actions/wrapper/wrapper_/wrapper"]
    # command: ["/bin/ls"]
    # args: ["-lR", "/app"]
#    command: ["/app/test"]
    imagePullPolicy: Always
  restartPolicy: Never
