apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: localhost:5000/test:bar
    command: ["/app/runner_/runner"]
#    command: ["/app/test"]
    imagePullPolicy: Always
  restartPolicy: Never
