apiVersion: v1
kind: Pod
metadata:
  name: wrapper
spec:
  containers:
  - name: wrapper
    image: localhost:5000/eval:2c13d7ad-9d6f-40ce-a489-4734db111eee
    command: ["/app/actions/wrapper/wrapper_/wrapper"]
    # command: ["/bin/ls"]
    # args: ["-lR", "/app"]
#    command: ["/app/test"]
    imagePullPolicy: Always
  restartPolicy: Never
