apiVersion: v1
kind: Pod
metadata:
  name: wrapper
spec:
  containers:
  - name: wrapper
    image: localhost:5000/eval:ac96c64f-6d00-4820-99b2-ac3a03af2757
    command: ["/app/actions/wrapper/wrapper_/wrapper"]
    # command: ["/bin/ls"]
    # args: ["-lR", "/app"]
#    command: ["/app/test"]
    imagePullPolicy: Always
  restartPolicy: Never
