apiVersion: v1
kind: Pod
metadata:
  name: wrapper
spec:
  containers:
  - name: wrapper
    image: localhost:5000/eval:15f81709-d9ee-4049-8fab-4f2917611d4d
    command: ["/app/actions/wrapper/wrapper_/wrapper"]
    # command: ["/bin/ls"]
    # args: ["-lR", "/app"]
#    command: ["/app/test"]
    imagePullPolicy: Always
  restartPolicy: Never
