apiVersion: v1
kind: Pod
metadata:
  name: wrapper
spec:
  containers:
  - name: wrapper
    image: localhost:5000/eval:7dc0ecd1-b961-4e9d-ae91-6dd621a43013
    command: ["/app/actions/wrapper/wrapper_/wrapper"]
    # command: ["/bin/ls"]
    # args: ["-lR", "/app"]
#    command: ["/app/test"]
    imagePullPolicy: Always
  restartPolicy: Never
