apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eval
  name: builder
  labels:
    app: eval-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eval-builder
  template:
    metadata:
      labels:
        app: eval-builder
    spec:
      volumes:
      - name: data
        hostPath:
          path: /data  # matches kind containerPath:
      - name: cluster-certificates
        secret:
          secretName: cluster-certificates
      serviceAccountName: builder-sa
      containers:
      - name: builder
        image: localhost:5000/main:dev
        ports:
        - containerPort: 50051
          name: grpc
        readinessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 15
          periodSeconds: 30
        volumeMounts:
        - name: data
          mountPath: /data
        - name: cluster-certificates
          mountPath: /app/Certs/
          readOnly: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: eval-builder
  name: builder-sa
  namespace: eval
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: eval-builder
  name: builder-cluster-role
rules:
  # Allow Metrics Scraper to get metrics from the Metrics server
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: eval-builder
  name: builder-cluster-role-binding
  namespace: eval
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: builder-cluster-role
subjects:
  - kind: ServiceAccount
    name: builder-sa
    namespace: eval
---
apiVersion: v1
kind: Service
metadata:
  namespace: eval
  name: eval-builder
  labels:
    app: eval-builder
spec:
  selector:
    app: eval-builder
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  type: NodePort
