apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eval
  name: runner
  labels:
    app: eval-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eval-runner
  template:
    metadata:
      labels:
        app: eval-runner
    spec:
      volumes:
      - name: data
        hostPath:
          path: /data  # matches kind containerPath:
      - name: cluster-certificates
        secret:
          secretName: cluster-certificates
      containers:
      - name: runner
        image: localhost:5000/main:dev
        ports:
        - containerPort: 50051
          name: grpc
        readinessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 15
          periodSeconds: 30
        volumeMounts:
        - name: data
          mountPath: /data
        - name: cluster-certificates
          mountPath: /data/eval/certificates
          readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  namespace: eval
  name: eval-runner
  labels:
    app: eval-runner
spec:
  selector:
    app: eval-runner
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  type: NodePort
