apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eval
  name: engine
  labels:
    app: eval-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eval-engine
  template:
    metadata:
      labels:
        app: eval-engine
    spec:
      volumes:
      - name: data
        hostPath:
          path: /data  # matches kind containerPath:
      - name: cluster-certificates
        secret:
          secretName: cluster-certificates
      - name: config-volume
        configMap:
          name: engine-config
      containers:
      - name: engine
        image: localhost:5000/main:dev
        ports:
        - containerPort: 50051
          name: grpc
        readinessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 15
          periodSeconds: 30
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: data
          mountPath: /data
        - name: cluster-certificates
          mountPath: /app/Certs/
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  namespace: eval
  name: eval-engine
  labels:
    app: eval-engine
spec:
  selector:
    app: eval-engine
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-config
  namespace: eval
data:
  config.yaml: |
      log.console.level: debug
