apiVersion: apps/v1
kind: Deployment
metadata:
  name: eval-engine-deployment
  labels:
    app: eval-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eval-engine
  template:
    metadata:
      labels:
        app: eval-engine
    spec:
      volumes:
      - name: data
        hostPath:
          path: /data  # matches kind containerPath:
      containers:
      - name: engine
        image: localhost:5001/main:dev
        ports:
        - containerPort: 50051
          name: grpc
        volumeMounts:
        - name: data
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: eval-engine
spec:
  selector:
    app: eval-engine
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
