baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'MLody'

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
#theme = ["docsy"]


[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
